source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in admin.gemspec.
gemspec

group :development do
  gem 'mysql2'
end

# To use a debugger
# gem 'byebug', group: [:development, :test]
gem 'graphql', '~> 2.2', '>= 2.2.5'
group :development do
  gem 'graphiql-rails'
end

gem "graphql-batch"

gem 'bootsnap', '>= 1.4.4', require: false
