# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("book.proto", :syntax => :proto3) do
    add_message "BookRequest" do
      optional :id, :int32, 1
    end
    add_message "BookResponse" do
      optional :title, :string, 1
    end
  end
end

module Book
  BookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BookRequest").msgclass
  BookResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BookResponse").msgclass
end
