# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hoge.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("hoge.proto", :syntax => :proto3) do
    add_message "HogeRequest" do
    end
    add_message "HogeResponse" do
      optional :message, :string, 1
    end
  end
end

module Hoge
  HogeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HogeRequest").msgclass
  HogeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HogeResponse").msgclass
end
